wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1679103248.501438
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 5
architecture:
  desc: null
  value: alexnet
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.0003
